-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 13:02:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weforvegan` DEFAULT CHARACTER SET utf8 ;
USE `weforvegan` ;

-- -----------------------------------------------------
-- Table `weforvegan`.`barcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weforvegan`.`barcode` (
  `pt_idx` INT NOT NULL,
  `pt_name` VARCHAR(500) NULL,
  `pt_rawmtr` VARCHAR(2000) NULL,
  `pt_barcode` VARCHAR(20) NULL,
  `pt_imgurl` VARCHAR(1000) NULL,
  `reg_date` DATETIME NULL,
  PRIMARY KEY (`pt_idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weforvegan`.`rawset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weforvegan`.`rawset` (
  `rs_idx` INT NOT NULL AUTO_INCREMENT,
  `rs_set` VARCHAR(500) NULL,
  `rs_cannoteattype` VARCHAR(200) NULL,
  PRIMARY KEY (`rs_idx`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weforvegan`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weforvegan`.`user` (
  `usr_idx` INT NOT NULL AUTO_INCREMENT,
  `usr_id` VARCHAR(20) NULL,
  `usr_pw` VARCHAR(100) NULL,
  `usr_name` VARCHAR(10) NULL,
  `usr_sex` ENUM('M', 'F') NULL,
  `usr_birth` CHAR(4) NULL,
  `usr_vegantype` VARCHAR(50) NULL,
  `usr_likeidx` VARCHAR(100) NULL,
  PRIMARY KEY (`usr_idx`),
  UNIQUE INDEX `usr_id_UNIQUE` (`usr_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weforvegan`.`qna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weforvegan`.`qna` (
  `qna_idx` INT NOT NULL AUTO_INCREMENT,
  `qna_content` VARCHAR(5000) NULL,
  `qna_mail` VARCHAR(50) NULL,
  `user_usr_idx` INT NOT NULL,
  PRIMARY KEY (`qna_idx`),
  INDEX `fk_qna_user1_idx` (`user_usr_idx` ASC) VISIBLE,
  CONSTRAINT `fk_qna_user1`
    FOREIGN KEY (`user_usr_idx`)
    REFERENCES `weforvegan`.`user` (`usr_idx`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weforvegan`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weforvegan`.`recipe` (
  `rp_idx` INT NOT NULL,
  `rp_name` VARCHAR(45) NOT NULL,
  `rp_source` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rp_idx`, `rp_name`, `rp_source`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weforvegan`.`snsrecipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weforvegan`.`snsrecipe` (
  `sns_url` VARCHAR(300) NOT NULL,
  `sns_imgurl` VARCHAR(3000) NULL,
  `recipe_rp_idx` INT NOT NULL,
  `recipe_rp_name` VARCHAR(45) NOT NULL,
  `recipe_rp_source` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recipe_rp_idx`, `recipe_rp_name`, `recipe_rp_source`),
  CONSTRAINT `fk_snsrecipe_recipe`
    FOREIGN KEY (`recipe_rp_idx` , `recipe_rp_name` , `recipe_rp_source`)
    REFERENCES `weforvegan`.`recipe` (`rp_idx` , `rp_name` , `rp_source`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weforvegan`.`apirecipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weforvegan`.`apirecipe` (
  `api_category` INT NULL,
  `api_howtocook` VARCHAR(20) NULL,
  `api_carbohydrate` INT NULL,
  `api_protein` INT NULL,
  `api_fat` INT NULL,
  `api_hashtag` VARCHAR(300) NULL,
  `api_imgurlsmall` VARCHAR(255) NULL,
  `api_imgurlbig` VARCHAR(255) NULL,
  `api_recipe` VARCHAR(5000) NULL,
  `api_ingredient` VARCHAR(50) NULL,
  `recipe_rp_idx` INT NOT NULL,
  `recipe_rp_name` VARCHAR(45) NOT NULL,
  `recipe_rp_source` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`recipe_rp_idx`, `recipe_rp_name`, `recipe_rp_source`),
  CONSTRAINT `fk_apirecipe_recipe1`
    FOREIGN KEY (`recipe_rp_idx` , `recipe_rp_name` , `recipe_rp_source`)
    REFERENCES `weforvegan`.`recipe` (`rp_idx` , `rp_name` , `rp_source`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
